version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/web/php-template
    networks:
      - app-network
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: cyxiaowu
      DB_USERNAME: user
      DB_PASSWORD: secret

  webserver:
    image: nginx:alpine
    ports:
      - "8084:80"
    volumes:
      - ./app:/home/web/php-template
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: cyxiaowu
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./app/mysql.sql:/home/mysql/mysql.sql
      - /Users/lincenying/web/mysqldb:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
